import { type NextPage } from "next";
import Head from "next/head";
import Booking from "./components/Booking";
import Navbar from "./components/Navbar";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Book an Appointment</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="min-h-screen bg-gradient-to-b from-tertiary-900 to-secondary-900">
				<Navbar />
				<Booking />
			</main>
		</>
	);
};

export default Home;
