import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Booking from "../components/Booking";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Book an Appointment</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="min-h-screen bg-gradient-to-b from-teal-200 to-sky-700">
				<Navbar />
				<Booking />
			</main>
		</>
	);
};

export default Home;
